// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mahrltahdntbfxncrhcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1haHJsdGFoZG50YmZ4bmNyaGNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODE5MDYsImV4cCI6MjA2MTg1NzkwNn0.R7j44aQ36t-m2HEYaqaFYt6kIHS5H2cbr0xg75pBhWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);